# EXPECT: no listed items
# EXPECT: succeeding add (1)
# EXPECT: 1 listed item (1)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
# EXPECT: failing add - mount point in use
Warning: mount point already in keyring
# EXPECT: 1 listed item (1)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
# EXPECT: succeeding add (2)
# EXPECT: 2 listed items (1,2)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
# EXPECT: succeeding add (3a)
# EXPECT: 3 listed items (1,2,3a)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3a
  mount at login : yes
  encfs config   : -
# EXPECT: succeeding add (3b)
# EXPECT: 4 listed items (1,2,3a,3b)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3a
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3b
  mount at login : yes
  encfs config   : -
# EXPECT: 2 succeeding mounts (3a,3b)
Mounting ./tenv/m3a: OK
Mounting ./tenv/m3b: OK
# EXPECT: 2 mounted paths (3a,3b)
encfs on ./tenv/m3a type fuse.encfs
encfs on ./tenv/m3b type fuse.encfs
# EXPECT: no mounted paths - all unmounted
# EXPECT: 4 succeeding mounts (1,2,3a,3b)
Mounting ./tenv/m1: OK
Mounting ./tenv/m2: OK
Mounting ./tenv/m3a: OK
Mounting ./tenv/m3b: OK
# EXPECT: 4 mounted paths (1,2,3a,3b)
encfs on ./tenv/m1 type fuse.encfs
encfs on ./tenv/m2 type fuse.encfs
encfs on ./tenv/m3a type fuse.encfs
encfs on ./tenv/m3b type fuse.encfs
# EXPECT: 4 failing mounts - already mounted
Mounting ./tenv/m1: mount point already in use
Mounting ./tenv/m2: mount point already in use
Mounting ./tenv/m3a: mount point already in use
Mounting ./tenv/m3b: mount point already in use
# EXPECT: no mounted paths - all unmounted
# EXPECT: 3 items (1,2,3b)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3b
  mount at login : yes
  encfs config   : -
# EXPECT: 3 items (1,2,3a)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3a
  mount at login : yes
  encfs config   : -
# EXPECT: 3 items (1,2,3a)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3a
  mount at login : yes
  encfs config   : -
# EXPECT: 1 failing mount (3a) - wrong password
Error decoding volume key, password incorrect
Mounting ./tenv/m3a: FAILED
# EXPECT: no mounted paths
# EXPECT: 3 items (1,2,3b)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3b
  mount at login : yes
  encfs config   : -
# EXPECT: 1 succeeding mount (3b)
Mounting ./tenv/m3b: OK
# EXPECT: 1 mounted path (3b)
encfs on ./tenv/m3b type fuse.encfs
# EXPECT: no mounted paths - all unmounted
# EXPECT: failing edit (3b->2) - mount point in use
Warning: mount point already in use
# EXPECT: 3 items (1,2,3b)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : yes
  encfs config   : -
* encfs path     : ./tenv/e3
  mount point    : ./tenv/m3b
  mount at login : yes
  encfs config   : -
# EXPECT: autostart on
autostart on
# EXPECT: 2 succeeding edits
# EXPECT: autostart on
autostart on
# EXPECT: autostart content
[Desktop Entry]
Comment=Mount EncFS folders configured in GNOME's keyring
Name=EncFS
Exec=gnome-encfs autostart
Version=1.0
Type=Application
X-GNOME-Autostart-enabled=true
Icon=folder

# EXPECT: 1 succeeding edits
# EXPECT: autostart off
autostart off
# EXPECT: succeeding add (1) with custom v5 config file location
# EXPECT: 1 listed item (1)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : no
  encfs config   : ./tenv/e1_encfs5
# EXPECT: 1 succeeding mounts (1)
Mounting ./tenv/m1: OK
# EXPECT: 1 mounted paths (1)
encfs on ./tenv/m1 type fuse.encfs
# EXPECT: no mounted paths - all unmounted
# EXPECT: succeeding edit (1) reset config file location
# EXPECT: 1 listed item (1)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : no
  encfs config   : -
# EXPECT: succeeding edit (1) with custom v5 config file location
# EXPECT: 1 listed item (1)
* encfs path     : ./tenv/e1
  mount point    : ./tenv/m1
  mount at login : no
  encfs config   : ./tenv/e1_encfs5
# EXPECT: succeeding remove (1)
# EXPECT: 0 items
# EXPECT: succeeding add (1) with custom v6 config file location
# EXPECT: 1 listed item (2)
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : no
  encfs config   : ./tenv/e2_encfs6.xml
# EXPECT: 1 succeeding mounts (2)
Mounting ./tenv/m2: OK
# EXPECT: 1 mounted paths (2)
encfs on ./tenv/m2 type fuse.encfs
# EXPECT: no mounted paths - all unmounted
# EXPECT: succeeding edit (2) reset config file location
# EXPECT: 1 listed item (2)
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : no
  encfs config   : -
# EXPECT: succeeding edit (2) with custom v6 config file locations
# EXPECT: 1 listed item (2)
* encfs path     : ./tenv/e2
  mount point    : ./tenv/m2
  mount at login : no
  encfs config   : ./tenv/e2_encfs6.xml
# EXPECT: succeeding remove (2)
# EXPECT: 0 items
# EXPECT: no listed items
# EXPECT: autostart off
autostart off
