# EXPECT: no listed items
# EXPECT: succeeding add (1)
# EXPECT: 1 listed item (1)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: failing add - mount point in use
Warning: mount point already in keyring
# EXPECT: 1 listed item (1)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: succeeding add (2)
# EXPECT: 2 listed items (1,2)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: succeeding add (3a)
# EXPECT: 3 listed items (1,2,3a)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3a
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: succeeding add (3b)
# EXPECT: 4 listed items (1,2,3a,3b)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3a
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3b
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: 2 succeeding mounts (3a,3b)
Mounting ./tenv/m3a: OK
Mounting ./tenv/m3b: OK
# EXPECT: 2 mounted paths (3a,3b)
./tenv/m3a type fuse.gocryptfs
./tenv/m3b type fuse.gocryptfs
# EXPECT: 2 succeding unmounts (3a,3b)
Unmounting ./tenv/m3a: OK
Unmounting ./tenv/m3b: OK
# EXPECT: no mounted paths - all unmounted
# EXPECT: 4 succeeding mounts (1,2,3a,3b)
Mounting ./tenv/m1: OK
Mounting ./tenv/m2: OK
Mounting ./tenv/m3a: OK
Mounting ./tenv/m3b: OK
# EXPECT: 4 mounted paths (1,2,3a,3b)
./tenv/m1 type fuse.gocryptfs
./tenv/m2 type fuse.gocryptfs
./tenv/m3a type fuse.gocryptfs
./tenv/m3b type fuse.gocryptfs
# EXPECT: 4 failing mounts - already mounted
Mounting ./tenv/m1: Mount point already in use
Mounting ./tenv/m2: Mount point already in use
Mounting ./tenv/m3a: Mount point already in use
Mounting ./tenv/m3b: Mount point already in use
# EXPECT: 4 succeeding unmounts (1,2,3a,3b)
Unmounting ./tenv/m1: OK
Unmounting ./tenv/m2: OK
Unmounting ./tenv/m3a: OK
Unmounting ./tenv/m3b: OK
# EXPECT: no mounted paths - all unmounted
# EXPECT: 3 items (1,2,3b)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3b
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: 3 items (1,2,3a)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3a
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: 3 items (1,2,3a)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3a
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: 1 failing mount (3a) - wrong password
Mounting ./tenv/m3a: FAILED
# EXPECT: no mounted paths
# EXPECT: 3 items (1,2,3b)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3b
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: 1 succeeding mount (3b)
Mounting ./tenv/m3b: OK
# EXPECT: 1 mounted path (3b)
./tenv/m3b type fuse.gocryptfs
# EXPECT: 1 succeeding unmount (3b)
Unmounting ./tenv/m3b: OK
# EXPECT: no mounted paths - all unmounted
# EXPECT: failing edit (3b->2) - mount point in use
Warning: mount point already in use
# EXPECT: 3 items (1,2,3b)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e2
MOUNT     : ./tenv/m2
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no

STASH     : ./tenv/e3
MOUNT     : ./tenv/m3b
CONFIG    : inline
AUTOMOUNT : yes
MOUNTED   : no
# EXPECT: autostart on
autostart on
# EXPECT: 2 succeeding edits
# EXPECT: autostart on
autostart on
# EXPECT: autostart content

Comment=Mount gocryptfs folders configured in GNOME's keyring
[Desktop Entry]
Exec=gnome-gocryptfs mount --auto
Icon=folder
Name=Mount gocryptfs
Type=Application
Version=1.0
X-GNOME-Autostart-enabled=true
# EXPECT: 1 succeeding edits
# EXPECT: autostart off
autostart off
# EXPECT: succeeding add (1) with custom config file location
# EXPECT: 1 listed item (1)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : ./tenv/e1_gocryptfs.conf
AUTOMOUNT : no
MOUNTED   : no
# EXPECT: 1 succeeding mounts (1)
Mounting ./tenv/m1: OK
# EXPECT: 1 mounted paths (1)
./tenv/m1 type fuse.gocryptfs
# EXPECT: 1 succeeding unmount (1)
Unmounting ./tenv/m1: OK
# EXPECT: no mounted paths - all unmounted
# EXPECT: succeeding edit (1) reset config file location
# EXPECT: 1 listed item (1)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : inline
AUTOMOUNT : no
MOUNTED   : no
# EXPECT: succeeding edit (1) with custom config file location
# EXPECT: 1 listed item (1)
STASH     : ./tenv/e1
MOUNT     : ./tenv/m1
CONFIG    : ./tenv/e1_gocryptfs.conf
AUTOMOUNT : no
MOUNTED   : no
# EXPECT: succeeding remove (1)
# EXPECT: 0 items
# EXPECT: no listed items
# EXPECT: autostart off
autostart off
