name: Run Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Run Tests
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-16.04, ubuntu-18.04]
        steps:
            - uses: actions/checkout@v2
            - name: Install gocryptfs
              env:
                  GOCRYPTFS_VERSION: 'v1.7.1'
              run: |
                  wget https://nuetzlich.net/gocryptfs-signing-key.pub
                  gpg --import gocryptfs-signing-key.pub
                  wget "https://github.com/rfjakob/gocryptfs/releases/download/${GOCRYPTFS_VERSION}/gocryptfs_${GOCRYPTFS_VERSION}_linux-static_amd64.tar.gz"
                  wget "https://github.com/rfjakob/gocryptfs/releases/download/${GOCRYPTFS_VERSION}/gocryptfs_${GOCRYPTFS_VERSION}_linux-static_amd64.tar.gz.asc"
                  gpg --verify "gocryptfs_${GOCRYPTFS_VERSION}_linux-static_amd64.tar.gz.asc"
                  tar xzf "gocryptfs_${GOCRYPTFS_VERSION}_linux-static_amd64.tar.gz"
                  sudo install gocryptfs /usr/local/bin
                  which gocryptfs
            - name: Install dependencies
              run: sudo apt install -y python3-xdg python3-gi dbus-x11 gnome-keyring libsecret-1-0
            - name: Run Tests
              run: |
                  export $(dbus-launch)
                  dbus-launch
                  gnome-keyring-daemon --start --daemonize --components=secrets
                  echo 'fake-password' | gnome-keyring-daemon -r -d --unlock
                  bash ./run.sh
              working-directory: ./tests/
