name: Run Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Run Tests
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-16.04, ubuntu-18.04]
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: sudo apt install -y python3-xdg python3-gi
            - name: Run Tests
              run: bash ./run.sh
              working-directory: ./tests/
